services:
  bot:
    restart: always
    build: .
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

volumes:
  mongo_data:
