services:
  bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dev.Dockerfile
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: ./pyproject.toml
    command: sh -c "watchmedo auto-restart --directory=./app --pattern=*.py --recursive -- python3 -m app.main"

  mongo:
    restart: unless-stopped
